### PR TITLE
I have a PlayStation Mobile game to add

### PR DESCRIPTION
**Pull request by EneRec**
The game is called "Oh, deer! Alpha"

It's an Outrun clone, it coluld be interesting to see it on pkgj

Tell me how can I give you the game so you can add it

I can't play it because my PS Vita hasn't got activated PSM but I can play PKGJ PSM games without that.

If I give the game to you, we all will be able to play

I paid for games like Musync which now is called Musynx, and I wasn't able to play because the PSM thing, so the only thing I can say is thank you for doing this project, you are a legend for the community!

I still have the old musync If you're interested, it has the old desing keyboard, thing we can only see in the PC version as an add! 

Thanks for reading and for yout time and effort!

### CODE REVIEW

**Comment by LiEnby** [comment]
Do you have a file in tm0:/psmdrm/act.dat ? Or simular? If you cant run the games yourself *due to activation missing* there isnt much you can do :-:

Btw this is *not* what pull requests are for.

**Comment by EneRec** [comment]
@KuromeSan Now I know I can activate PSM mobile games with NoPsmDrm, anyway I have Oh, deer! Alpha and Musync mobile games from EU if you want to add them to the PKGJ store

Sorry for the inconvenience

**Comment by LiEnby** [comment]
NoPsmDrm does NOT activate anything-
you can dump psm games only if your console *IS* offically PSM activated, and the games acturaly run only then can you dump the games license data and put it into pkgj- if you cant run them then NoPsmDrm can do nothing for you

you need to check for activation data in tm0:/psmdrm/act.dat

**Comment by EneRec** [comment]
I haven't got my PS Mobile activated, there's no act.dat and Idk where can I generate a new one, but for some reason NoPsmDrm allows me to play the PSM games I bought, so it's fixed for me

**Comment by LiEnby** [comment]
Check ux0:/data for your games content_id then..?

**Pull request closed without merging**
